---
deployment:
  tasks:
    - export DEPLOYPATH=/home/autg6277/staging.automationweek-ppns.org
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp -R * $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH/ 2>/dev/null || :
    - /bin/cp public/.htaccess $DEPLOYPATH/public/ 2>/dev/null || :



