---
deployment:
  tasks:
    - export BRANCH=$(git branch --show-current || echo dev)
    - if [ "$BRANCH" = "main" ]; then export DEST=/home/autg6277/public_html; else export DEST=/home/autg6277/public_html/staging.automationweek-ppns.org; fi
    - /bin/cp -Rf config public src schema.sql .htaccess $DEST/








